#!/bin/sh

if [ -x /usr/sbin/setcap ]; then /usr/sbin/setcap cap_sys_nice=pe /usr/local/frc/JRE/bin/java ; fi

echo /usr/local/frc/JRE/lib/aarch32/jli > /etc/ld.so.conf.d/java_libs.conf
echo /usr/local/frc/JRE/lib/aarch32 >> /etc/ld.so.conf.d/java_libs.conf

if [ -x /sbin/ldconfig ]; then /sbin/ldconfig ; fi
